### ISSUE TITLE
Plugin doesnt start - 1.19

### ISSUE THREAD

**Issue by skrevt** [LuminaGames/PlayerLogger#4]
Hey. got this error on my Server
Serverversion: 1.19 - newest PLugin version

![Screenshot_9](https://user-images.githubusercontent.com/88806692/184547183-87266ccf-408c-4ce4-85ac-d7180a1a20f9.png)
![Screenshot_9](https://user-images.githubusercontent.com/88806692/184547192-73304d92-8ba2-49e7-87fa-8d6f4833f75e.png)

**Comment by COMP-HACK** [comment]
Thank You for contacting me. I have Updated the Jar on the plugin page. The Configuration File dosent initialize first and database tried to get a boolean value from the config which resulted in a null value and breaking the plugin. I request you to download the latest version from the spigot page [here](https://www.spigotmc.org/resources/player-logger-mysql-support-added.103033/)

**Comment by COMP-HACK** [comment]
There is also a known bug where if you dont put the player's name of which logs you want to get. It will give an error. Just put all the required arguments in the command.
