### ISSUE TITLE
Only Logs Chat and Commands not Players

### ISSUE THREAD

**Issue by Walle187** [LuminaGames/PlayerLogger#9]
As the title says it only Logs the chat and the commands. Players are not being logged (Name, UUID, Ip, Join Location, Quit Location, etc.).
I use MySql with Plugin version 1.1.6 and Paper 1.20.2.

**Comment by VedantMulay** [comment]
Are there any errors in the console?
The plugin is only tested for 1.20.1
I'll have to check if it works on later versions the game

**Comment by Walle187** [comment]
I checked the Logs and after 9hours of not joining the Server I got an error. [Error Logs](https://pastebin.com/XJwCpjjE). I restarted the Server and enabled Debug Mode. [This Log](https://pastebin.com/kWkuaggy). It still does not work.

**Comment by VedantMulay** [comment]
Thanks for reporting the issue. I just tested out the plugin. The issue is with the MySQL Database. For temporary basis you can turn off the MySQL and use SQLite. I will fix it asap.
